/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default'];
    AppHeader: typeof import('./src/components/AppHeader.vue')['default'];
    AppHeaderMobile: typeof import('./src/components/AppHeaderMobile.vue')['default'];
    ContentWrapper: typeof import('./src/components/ContentWrapper.vue')['default'];
    CookieNotice: typeof import('./src/components/CookieNotice.vue')['default'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
