export const grouprelationsList = [
  {
    name: '卞乃猛',
    email: '@biannm',
    url: '',

    group: [
      'sig-Rust',
      'sig-peri-modules',
      'sig-python-modules',
      'sig-Java',
      'sig-nodejs',
      'dev-utils',
      'Runtime',
    ],
  },
  {
    name: '陈祺德',
    email: '@dillon_chen',
    url: '',
    group: [
      'dev-utils',
      'Runtime',
      'sig-libboundscheck',
      'System-tool',
      'sig-golang',
    ],
  },
  {
    name: '曹  志',
    email: '@georgecao',
    url: '',
    group: [
      'sig-ruby',
      'Compiler',
      'Programming-language',
      'A-tune',
      'Storage',
    ],
  },
  {
    name: '侯  健',
    email: '@hjimmy',
    url: '',
    group: [
      'sig-libboundscheck',
      'System-tool',
      'Base-service',
      'Computing',
      'sig-ops',
      'sig-bootstrap',
    ],
  },
  {
    name: '胡  峰',
    email: '@solarhu',
    url: '',
    group: [
      'Networking',
      'sig-security-facility',
      'sig-mate-desktop',
      'sig-high-performance-network',
      'sig-confidential-computing',
    ],
  },
  {
    name: '胡欣蔚',
    email: '@shinwell_hu',
    url: '',
    group: [
      'sig-Rust',
      'sig-peri-modules',
      'sig-python-modules',
      'sig-Java',
      'sig-nodejs',
      'dev-utils',
      'Runtime',
    ],
  },
  {
    name: '刘寿永',
    email: '@pangbanme',
    url: '',
    group: [
      'dev-utils',
      'Runtime',
      'sig-libboundscheck',
      'System-tool',
      'sig-golang',
    ],
  },
  {
    name: '李永强',
    email: '@charlie_li',
    url: '',
    group: [
      'sig-ruby',
      'Compiler',
      'Programming-language',
      'A-tune',
      'Storage',
    ],
  },
  {
    name: '石  勇',
    email: '@stonefly128',
    url: '',
    group: [
      'sig-libboundscheck',
      'System-tool',
      'Base-service',
      'Computing',
      'sig-ops',
      'sig-bootstrap',
    ],
  },
  {
    name: '王建民',
    email: '@jianminw',
    url: '',
    group: [
      'Networking',
      'sig-security-facility',
      'sig-mate-desktop',
      'sig-high-performance-network',
      'sig-confidential-computing',
    ],
  },
  {
    name: '王志钢',
    email: '@cellfaint',
    url: '',
    group: [
      'sig-Rust',
      'sig-peri-modules',
      'sig-python-modules',
      'sig-Java',
      'sig-nodejs',
      'dev-utils',
      'Runtime',
    ],
  },
  {
    name: '彭成寒',
    email: '@pengryan',
    url: '',
    group: [
      'dev-utils',
      'Runtime',
      'sig-libboundscheck',
      'System-tool',
      'sig-golang',
    ],
  },
  {
    name: '任  慰',
    email: '@wu_fengguang',
    url: '',
    group: [
      'sig-ruby',
      'Compiler',
      'Programming-language',
      'A-tune',
      'Storage',
    ],
  },
  {
    name: '吴峰光',
    email: '@hjimmy',
    url: '',
    group: [
      'sig-libboundscheck',
      'System-tool',
      'Base-service',
      'Computing',
      'sig-ops',
      'sig-bootstrap',
    ],
  },
  {
    name: '王伶卓',
    email: '@solarhu',
    url: '',
    group: [
      'Networking',
      'sig-security-facility',
      'sig-mate-desktop',
      'sig-high-performance-network',
      'sig-confidential-computing',
    ],
  },
  {
    name: '魏  刚',
    email: '@gwei3',
    url: '',
    group: [
      'sig-Rust',
      'sig-peri-modules',
      'sig-python-modules',
      'sig-Java',
      'sig-nodejs',
      'dev-utils',
      'Runtime',
    ],
  },
  {
    name: '谢秀奇',
    email: '@xiexiuqi',
    url: '',
    group: [
      'dev-utils',
      'Runtime',
      'sig-libboundscheck',
      'System-tool',
      'sig-golang',
    ],
  },
  {
    name: '熊  伟',
    email: '@myeuler',
    url: '',
    group: [
      'sig-libboundscheck',
      'System-tool',
      'Base-service',
      'Computing',
      'sig-ops',
      'sig-bootstrap',
    ],
  },
  {
    name: '叶青龙',
    email: '@yeqinglong01',
    url: '',
    group: [
      'Networking',
      'sig-security-facility',
      'sig-mate-desktop',
      'sig-high-performance-network',
      'sig-confidential-computing',
    ],
  },
  {},
];
export const urlObj = {
  'Networking': '',
  'sig-Rust': '',
  'sig-peri-modules': '',
  'sig-python-modules': '',
  'sig-Java': '',
  'sig-nodejs': '',
  'dev-utils': '',
  'Runtime': '',
  'sig-security-facility': '',
  'sig-mate-desktop': '',
  'sig-high-performance-network': '',
  'sig-confidential-computing': '',
  'sig-libboundscheck': '',
  'System-tool': '',
  'sig-golang': '',
  'sig-ruby': '',
 'Compiler': '',
  'Programming-language': '',
  'A-tune': '',
  'Storage': '',
  'Base-service':'',
  'sig-ops':'',
  'sig-bootstrap':'',

};
